version: '3'

services:
  streamlit_app:
    build: .
    ports:
      - "8502:8502"
    volumes:
      - ./notebooks:/app/notebooks
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Pass the environment variable to the container
    command: python -m streamlit run /app/app.py --server.headless true --server.address 0.0.0.0 --server.port 8502
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"